### ISSUE TITLE
verbe défectif pleuvoir fait planter

### ISSUE THREAD

**Issue by fredericpierron** [bretttolbert/verb-conjugate-fr#2]
Le verbe pleuvoir fait planter le python.

**Comment by bretttolbert** [comment]
Merci d'avoir signalé ce bug. Je l'ai corrigé avec mon dernier commit [ca259b5](https://github.com/bretttolbert/verb-conjugate-fr/commit/ca259b558534052914f349c3c2aa9c6921408b0a). Les verbes impersonnels ne devraient plus le faire planter.

**Comment by fredericpierron** [comment]
Pleuvoir fonctionne.
Mais neiger, grêler, bruiner sont conjugués comme des verbes à toutes les personnes.

**Comment by bretttolbert** [comment]
Merci à nouveau ! J'ai corrigé les conjugaisons pour neiger, grêler et bruiner [a4aca38](https://github.com/bretttolbert/verb-conjugate-fr/commit/a4aca38478d59ae1f74595ef1fc55a8569e09342) et j'ai corrigé la conjugaison en passé-compose pour les verbes impersonnels [59508ea](https://github.com/bretttolbert/verb-conjugate-fr/commit/59508ead693c408a396c874d66a50528a4c57612).
